 ########################################################
    # Register Linux hosts
    ########################################################
    - name: Register Linux hosts
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ zabbix_api_token }}"
        body: |
          {
            "jsonrpc": "2.0",
            "method": "host.create",
            "params": {
              "host": "{{ hostvars[item].ansible_hostname }}",
              "interfaces": [{
                "type": 1,
                "main": 1,
                "useip": 1,
                "ip": "{{ hostvars[item].ansible_default_ipv4.address }}",
                "dns": "",
                "port": "10050"
              }],
              "groups": [{ "groupid": "{{ linux_group_id }}" }],
              "templates": [{ "templateid": "{{ linux_template_id }}" }]
            },
            "id": 1
          }
      loop: "{{ groups['linux'] }}"
      ignore_errors: yes

    ########################################################
    # Register Windows hosts
    ########################################################
    - name: Register Windows hosts
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ zabbix_api_token }}"
        body: |
          {
            "jsonrpc": "2.0",
            "method": "host.create",
            "params": {
              "host": "{{ hostvars[item].ansible_hostname }}",
              "interfaces": [{
                "type": 1,
                "main": 1,
                "useip": 1,
                "ip": "{{ item }}",
                "dns": "",
                "port": "10050"
              }],
              "groups": [{ "groupid": "{{ windows_group_id }}" }],
              "templates": [{ "templateid": "{{ windows_template_id }}" }]
            },
            "id": 1
          }
      loop: "{{ groups['windows'] }}"
      ignore_errors: yes
